const HISTORY_2024=[
 {id:'polarsteps-2024-arnold',date:'2024-07-27',contactId:'mfst-ed-decker',title:'Arnold Baptist Tabernacle | Arnold, MO',fields:{preached:'yes',sermons:["He Inclines, So Don't Recline"],outreach:'Soulwinning with the church',journal:'We arrived on Saturday and went soulwinning with the church (not enough people to do a Bible handout). Andrew preached all day Sunday. We had plans to do a Bible handout on Monday morning, but it rained, so Andrew went to the church and worked until noon.'}},
 {id:'polarsteps-2024-football-camp',date:'2024-08-04',contactId:'mfst-dan-woodward',title:'Football Camp | First Baptist Church of Dwight',fields:{preached:'no',journal:'Andrew worked the week of Football Camp and helped in the media department. Shabba Dabba Day!'}},
 {id:'polarsteps-2024-ponce',date:'2024-08-19',contactId:'mfst-jerrod-montgomery',title:'Templo Bautista Independiente | Ponce, Puerto Rico',fields:{preached:'yes',sermons:['Heaps Upon Heaps',"I Just Can't Help It!",'Benefits of Abiding'],handout:'yes',outreach:'Two Bible handouts during the anniversary conference',salvations:15,biblesPassed:70,journal:'We arrived in Puerto Rico on Monday after a full day of travel. Tuesday morning, we went to the church and helped set up for the conference. Wednesday, Thursday and Friday evenings were services for the church anniversary conference. Andrew preached through an interpreter. On Friday, Andrew, Abby, Bro. Jerrod and Jack tried the first Bible handout; in two hours, 32 Bibles were handed out and one person was saved. Many people stopped, but the language barrier made witnessing difficult. On Saturday, seven or eight people from the church joined the Bible handout. In one hour, the group ran out after handing out 38 Bibles, and 14 people were saved. Praise the Lord!'}},
 {id:'polarsteps-2024-abq',date:'2024-09-04',contactId:'mfst-matt-hudson',title:'Bella Vista Baptist Church | Albuquerque, NM',fields:{preached:'yes',handout:'yes',outreach:'Labor Day Conference and Bible handout',salvations:2,biblesPassed:50,support:'yes',journal:'We were able to spend almost a week and a half in Albuquerque. Andrew drove down and arrived August 30; Abby flew down with Lexy on September 1. We took part in the Labor Day Conference. Andrew presented and preached Wednesday night, when the church voted to take us on for support. Twenty-four church members came for the Saturday Bible handout, so we split into two groups. It felt a little crazy, but it went well: 50 Bibles were handed out, with five gospel presentations and two people saved. We were at Bella Vista Baptist Church again Sunday and especially enjoyed extra time with Mom and Dad. On Friday, Dad took us on the tram to the top of the mountain; it was incredible.'}},
 {id:'polarsteps-2024-abilene',date:'2024-09-11',contactId:'abilene-baptist-church-abilene-tx',title:'Abilene Baptist Church | Abilene, TX',fields:{handout:'yes',outreach:'Missions conference and Bible handout',salvations:4,biblesPassed:32,journal:'We left Albuquerque Tuesday morning and headed for Texas, arriving Tuesday evening. Wednesday morning we ran errands and then checked into the hotel for the missions conference. It was a great week with Pastor Avery Barney, his wife Harmony, and their children. Fellow missionaries included Jared and Tiffany Stalnaker and Jordan Smith. The keynote speaker was Bro. Dan Caldwell, whose family we enjoyed getting to know. The church was very kind and planned family activities Thursday and Friday morning. We visited the Abilene Zoo Thursday and Primetime Friday, including the CuriouCity imagination playground. Lexy loved dressing up, pretending to hold different occupations, and bowling a few frames with Andrew. The church was very friendly and it was a blessing getting to know the people. At Saturday’s Bible handout, 32 Bibles were distributed and four people were saved. Praise the Lord!'}},
 {id:'polarsteps-2024-elgin',date:'2024-09-21',contactId:'mfst-phil-cavanaugh',title:'Old Paths Conference | Northwest Bible Baptist Church',fields:{preached:'no',outreach:'Soulwinning and Old Paths Conference',journal:'We arrived in Elgin for the 50th anniversary Golden Weekend. Friday night, we went to dinner with Abby’s parents and siblings to honor their anniversary. Saturday morning, Abby went soulwinning with the church while Andrew stayed home sick. There was a meal and service Saturday night, and the celebration continued all day Sunday. Old Paths ran Monday through Thursday. It was a blessing to see many friends and be encouraged by the sessions and messages.'}},
 {id:'polarsteps-2024-sandusky',date:'2024-09-28',contactId:'mfst-david-oh-young',title:'Bible Baptist Church | Sandusky, OH',fields:{preached:'yes',sermons:['My God Is… (A Rock, a Rose, a Light, a Star)'],handout:'yes',outreach:'Bible handout at Walmart and a nearby mall parking lot',salvations:4,biblesPassed:26,journal:'We arrived in Sandusky Friday afternoon. Andrew went to dinner with Pastor David Young while Abby and Lexy stayed at the hotel. Saturday morning, we did a Bible handout with the pastor’s family, an older lady, Mrs. Brown, and us. Rain interrupted the Walmart setup, and after returning later an employee asked us to leave, so we moved to a nearby mall parking lot. Twenty-six Bibles were handed out and four people were saved. Andrew preached Sunday School, Sunday morning, and Sunday afternoon, presenting the “My God Is…” series: A Rock, a Rose, a Light, and a Star. We sang “Lord, You’re the Best Thing” and “Be Not Afraid.”'}},
 {id:'polarsteps-2024-fond-du-lac',date:'2024-10-02',end:'2024-10-06',contactId:'mfst-jack-barber',title:'Lighthouse Bible Baptist Church | Fond du Lac, WI',fields:{preached:'yes',handout:'yes',outreach:'Revival and Bible handout',salvations:1,journal:'Andrew preached a revival Wednesday through Sunday in Fond du Lac, Wisconsin. It was a wonderful week with the people of Lighthouse Bible Baptist Church, and we were blessed to be there. One person was saved during Saturday’s Bible handout. We never want to take for granted the blessing and provision of God. We enjoyed fellowship with Jack and Taylor Barber and, Lord willing, will return next year.'}},
 {id:'polarsteps-2024-rendon',date:'2024-10-10',contactId:'mfst-chris-winkle',title:'Bible Baptist Church of Rendon | Fort Worth, TX',fields:{preached:'yes',handout:'yes',outreach:'Bible Handout Conference',salvations:1,biblesPassed:7,lodging:'yes',journal:'The church allowed us to stay in its very nice missions apartment during the Bible Handout Conference. Andrew preached Wednesday night. It was good to see Pastor Anglea and Ross, and we met many new people and, Lord willing, scheduled additional meetings. We had to leave for Houston at noon Saturday, but Andrew participated in the Bible handout for a while. Seven Bibles were handed out and one person was saved.'}},
 {id:'polarsteps-2024-la-porte',date:'2024-10-13',contactId:'mfst-danny-traxler',title:'Underwood Baptist Church | La Porte, TX',fields:{journal:'We attended the missions conference with Underwood Baptist Church and Pastor Traxler and were able to be with the Nettervilles. The church was extremely generous, giving us a giant snack box and a CityPass with admission to several Houston attractions. We visited the Boardwalk Monday and the Children’s Museum Wednesday with the Nettervilles. Bro. Netterville had several appointments while we were there, and they planned to remain in Houston for several months for cancer treatments.'}},
 {id:'polarsteps-2024-lake-worth',date:'2024-10-17',contactId:'mfst-patrick-bujak',title:'Metropolitan Baptist Church | Lake Worth, TX',fields:{preached:'yes',handout:'yes',outreach:'Missions conference and Bible handout',biblesPassed:9,journal:'We were scheduled to attend this missions conference with the Nettervilles, but they remained in Houston for cancer treatments. We were nervous because we had not communicated with the church about the conference and arrived a day late, reaching the Thursday evening service. We later discovered Pastor Bujak was the singer on a CD Andrew loves, which helped break the ice. The conference used a different format, featuring many area preachers in the mornings. Although the music standards differed from ours, the church has a strong burden for missions and soulwinning. We met the Sargents from Washington, who were a great blessing. Andrew was asked to preach Sunday School. Nine Bibles were handed out Saturday.'}}
];

const meaningful=v=>v!==undefined&&v!==null&&v!==''&&v!=='unknown';
export function applyPolarstepsHistory2024(state){
 if(!Array.isArray(state.calendarMeetings))state.calendarMeetings=[];
 for(const entry of HISTORY_2024){
  let meeting=state.calendarMeetings.find(m=>m.contactId===entry.contactId&&m.date===entry.date);
  if(!meeting){meeting={id:entry.id,title:entry.title,date:entry.date,end:entry.end||entry.date,contactId:entry.contactId,kind:'meeting',source:'Polarsteps journal'};state.calendarMeetings.push(meeting);}
  const current=meeting.debrief||{},fields=entry.fields,journal=current.journal&&current.journal.includes(fields.journal)?current.journal:[current.journal,fields.journal].filter(Boolean).join('\n\n');
  meeting.debrief={...current,status:current.status||'completed',preached:meaningful(current.preached)?current.preached:(fields.preached||'unknown'),sermons:[...new Set([...(current.sermons||[]),...(fields.sermons||[])])],handout:meaningful(current.handout)?current.handout:(fields.handout||'unknown'),outreach:current.outreach||fields.outreach||'',salvations:current.salvations??fields.salvations??null,biblesPassed:current.biblesPassed??fields.biblesPassed??null,visitors:meaningful(current.visitors)?current.visitors:'unknown',lodging:meaningful(current.lodging)?current.lodging:(fields.lodging||'unknown'),support:meaningful(current.support)?current.support:(fields.support||'unknown'),journal,photo:current.photo||'',polarstepsUpdated:true,completedAt:current.completedAt||'2026-09-26T00:00:00.000Z',snoozedUntil:'',polarstepsImport:true};
 }
 state.polarstepsHistory2024Applied=true;
 return state;
}
