const HISTORY_2024=[
 {id:'polarsteps-2024-arnold',date:'2024-07-27',contactId:'mfst-ed-decker',title:'Arnold Baptist Tabernacle | Arnold, MO',fields:{preached:'yes',sermons:["He Inclines, So Don't Recline"],outreach:'Soulwinning with the church',journal:'We arrived on Saturday and went soulwinning with the church (not enough people to do a Bible handout). Andrew preached all day Sunday. We had plans to do a Bible handout on Monday morning, but it rained, so Andrew went to the church and worked until noon.'}},
 {id:'polarsteps-2024-football-camp',date:'2024-08-04',contactId:'mfst-dan-woodward',title:'Football Camp | First Baptist Church of Dwight',fields:{preached:'no',journal:'Andrew worked the week of Football Camp and helped in the media department. Shabba Dabba Day!'}},
 {id:'polarsteps-2024-ponce',date:'2024-08-19',contactId:'mfst-jerrod-montgomery',title:'Templo Bautista Independiente | Ponce, Puerto Rico',fields:{preached:'yes',sermons:['Heaps Upon Heaps',"I Just Can't Help It!",'Benefits of Abiding'],handout:'yes',outreach:'Two Bible handouts during the anniversary conference',salvations:15,biblesPassed:70,journal:'We arrived in Puerto Rico on Monday after a full day of travel. Tuesday morning, we went to the church and helped set up for the conference. Wednesday, Thursday and Friday evenings were services for the church anniversary conference. Andrew preached through an interpreter. On Friday, Andrew, Abby, Bro. Jerrod and Jack tried the first Bible handout; in two hours, 32 Bibles were handed out and one person was saved. Many people stopped, but the language barrier made witnessing difficult. On Saturday, seven or eight people from the church joined the Bible handout. In one hour, the group ran out after handing out 38 Bibles, and 14 people were saved. Praise the Lord!'}},
 {id:'polarsteps-2024-abq',date:'2024-09-04',contactId:'mfst-matt-hudson',title:'Bella Vista Baptist Church | Albuquerque, NM',fields:{preached:'yes',handout:'yes',outreach:'Labor Day Conference and Bible handout',salvations:2,biblesPassed:50,support:'yes',journal:'We were able to spend almost a week and a half in Albuquerque. Andrew drove down and arrived August 30; Abby flew down with Lexy on September 1. We took part in the Labor Day Conference. Andrew presented and preached Wednesday night, when the church voted to take us on for support. Twenty-four church members came for the Saturday Bible handout, so we split into two groups. It felt a little crazy, but it went well: 50 Bibles were handed out, with five gospel presentations and two people saved. We were at Bella Vista Baptist Church again Sunday and especially enjoyed extra time with Mom and Dad. On Friday, Dad took us on the tram to the top of the mountain; it was incredible.'}},
 {id:'polarsteps-2024-abilene',date:'2024-09-11',contactId:'abilene-baptist-church-abilene-tx',title:'Abilene Baptist Church | Abilene, TX',fields:{handout:'yes',outreach:'Missions conference and Bible handout',salvations:4,biblesPassed:32,journal:'We left Albuquerque Tuesday morning and headed for Texas, arriving Tuesday evening. Wednesday morning we ran errands and then checked into the hotel for the missions conference. It was a great week with Pastor Avery Barney, his wife Harmony, and their children. Fellow missionaries included Jared and Tiffany Stalnaker and Jordan Smith. The keynote speaker was Bro. Dan Caldwell, whose family we enjoyed getting to know. The church was very kind and planned family activities Thursday and Friday morning. We visited the Abilene Zoo Thursday and Primetime Friday, including the CuriouCity imagination playground. Lexy loved dressing up, pretending to hold different occupations, and bowling a few frames with Andrew. The church was very friendly and it was a blessing getting to know the people. At Saturday’s Bible handout, 32 Bibles were distributed and four people were saved. Praise the Lord!'}},
 {id:'polarsteps-2024-elgin',date:'2024-09-21',contactId:'mfst-phil-cavanaugh',title:'Old Paths Conference | Northwest Bible Baptist Church',fields:{preached:'no',outreach:'Soulwinning and Old Paths Conference',journal:'We arrived in Elgin for the 50th anniversary Golden Weekend. Friday night, we went to dinner with Abby’s parents and siblings to honor their anniversary. Saturday morning, Abby went soulwinning with the church while Andrew stayed home sick. There was a meal and service Saturday night, and the celebration continued all day Sunday. Old Paths ran Monday through Thursday. It was a blessing to see many friends and be encouraged by the sessions and messages.'}},
 {id:'polarsteps-2024-sandusky',date:'2024-09-28',contactId:'mfst-david-oh-young',title:'Bible Baptist Church | Sandusky, OH',fields:{preached:'yes',sermons:['My God Is… (A Rock, a Rose, a Light, a Star)'],handout:'yes',outreach:'Bible handout at Walmart and a nearby mall parking lot',salvations:4,biblesPassed:26,journal:'We arrived in Sandusky Friday afternoon. Andrew went to dinner with Pastor David Young while Abby and Lexy stayed at the hotel. Saturday morning, we did a Bible handout with the pastor’s family, an older lady, Mrs. Brown, and us. Rain interrupted the Walmart setup, and after returning later an employee asked us to leave, so we moved to a nearby mall parking lot. Twenty-six Bibles were handed out and four people were saved. Andrew preached Sunday School, Sunday morning, and Sunday afternoon, presenting the “My God Is…” series: A Rock, a Rose, a Light, and a Star. We sang “Lord, You’re the Best Thing” and “Be Not Afraid.”'}},
 {id:'polarsteps-2024-fond-du-lac',date:'2024-10-02',end:'2024-10-06',contactId:'mfst-jack-barber',title:'Lighthouse Bible Baptist Church | Fond du Lac, WI',fields:{preached:'yes',handout:'yes',outreach:'Revival and Bible handout',salvations:1,journal:'Andrew preached a revival Wednesday through Sunday in Fond du Lac, Wisconsin. It was a wonderful week with the people of Lighthouse Bible Baptist Church, and we were blessed to be there. One person was saved during Saturday’s Bible handout. We never want to take for granted the blessing and provision of God. We enjoyed fellowship with Jack and Taylor Barber and, Lord willing, will return next year.'}},
 {id:'polarsteps-2024-rendon',date:'2024-10-10',contactId:'mfst-chris-winkle',title:'Bible Baptist Church of Rendon | Fort Worth, TX',fields:{preached:'yes',handout:'yes',outreach:'Bible Handout Conference',salvations:1,biblesPassed:7,lodging:'yes',journal:'The church allowed us to stay in its very nice missions apartment during the Bible Handout Conference. Andrew preached Wednesday night. It was good to see Pastor Anglea and Ross, and we met many new people and, Lord willing, scheduled additional meetings. We had to leave for Houston at noon Saturday, but Andrew participated in the Bible handout for a while. Seven Bibles were handed out and one person was saved.'}},
 {id:'polarsteps-2024-la-porte',date:'2024-10-13',contactId:'mfst-danny-traxler',title:'Underwood Baptist Church | La Porte, TX',fields:{journal:'We attended the missions conference with Underwood Baptist Church and Pastor Traxler and were able to be with the Nettervilles. The church was extremely generous, giving us a giant snack box and a CityPass with admission to several Houston attractions. We visited the Boardwalk Monday and the Children’s Museum Wednesday with the Nettervilles. Bro. Netterville had several appointments while we were there, and they planned to remain in Houston for several months for cancer treatments.'}},
 {id:'polarsteps-2024-lake-worth',date:'2024-10-17',contactId:'mfst-patrick-bujak',title:'Metropolitan Baptist Church | Lake Worth, TX',fields:{preached:'yes',handout:'yes',outreach:'Missions conference and Bible handout',biblesPassed:9,journal:'We were scheduled to attend this missions conference with the Nettervilles, but they remained in Houston for cancer treatments. We were nervous because we had not communicated with the church about the conference and arrived a day late, reaching the Thursday evening service. We later discovered Pastor Bujak was the singer on a CD Andrew loves, which helped break the ice. The conference used a different format, featuring many area preachers in the mornings. Although the music standards differed from ours, the church has a strong burden for missions and soulwinning. We met the Sargents from Washington, who were a great blessing. Andrew was asked to preach Sunday School. Nine Bibles were handed out Saturday.'}}
];

const HISTORY_2025=[
 {id:'polarsteps-2025-friendship-conference',targetId:'tcfcv8tncm7vtk4tguorg6f9fs',date:'2025-01-31',contactId:'mfst-jerry-power',title:'Friendship Baptist Church Missions Conference',fields:{journal:'I traveled alone because Haddon was on oxygen. When I arrived at the missions conference, my car broke down. The pastor drove me to several dealerships until I found a 2017 Toyota Sienna. The church generously gave $5,000 toward the purchase, and I borrowed $4,000 from Brother Netterville for the remainder. Looking back, I can see how God worked everything out through the unexpected. Despite the car trouble, it was a very good conference, and it was especially good to see the Shrouts, missionaries to Japan, again.'}},
 {id:'polarsteps-2025-friendship-training',targetId:'tcfcv8tncm7vtk4tguorg6f9fs',date:'2025-01-31',contactId:'mfst-jerry-power',title:'Friendship Baptist Church',fields:{outreach:'Soulwinning training',support:'yes',journal:'I returned for soulwinning training. The people were very kind, and the pastor took me to the rodeo. I was scheduled to teach two soulwinning sessions, but the second was canceled because of widespread sickness. With the evening free, I attended Parkside’s Wednesday service and caught up with Ethan Graham and Gilbert Fernandez. Shortly after this meeting, another meeting was rescheduled and the church took us on for monthly support.'}},
 {id:'polarsteps-2025-bellefontaine',targetId:'o5gvt1jmkjb3v8br048nb02g28',date:'2025-08-24',contactId:'mfst-jim-frost',title:'Solid Rock Baptist Church Revival | Bellefontaine, OH',fields:{preached:'yes',sermons:['Reporting as Eligible','Activating the Trinity','One Chose to Leave, the Other to Cleave','The Proven Pattern','Benefits of Abiding',"I Just Can’t Help It"],handout:'yes',outreach:'Revival services and Bible handouts Monday and Wednesday',journal:'Revival services ran Sunday through Wednesday at Solid Rock Baptist Church with Pastor Jim Frost. Bible handouts were held Monday and Wednesday, with more than 15 Bibles distributed each time and multiple salvations. Visitors came because of the handouts, and more church members joined the second handout after seeing the first one’s success. Tuesday included a golf outing with Pastor Frost.'}},
 {id:'polarsteps-2025-labor-day',targetId:'8pklbd9i0punmn0v3amkk8j3a8',date:'2025-09-01',contactId:'mfst-matt-hudson',title:'Labor Day Conference | Bella Vista Baptist Church',fields:{preached:'no',lodging:'yes',journal:'We traveled from Ohio to Albuquerque, stopping in Amarillo to visit Pastor Copeland on Sunday. At Bella Vista Baptist Church’s Labor Day Conference with Pastor Matt Hudson, I participated as an attendee rather than a speaker. Brother Lewis Horton was the host speaker, and seven different preachers spoke on Labor Day. Sunday morning we attended New Heights Baptist Church without preaching; Sunday evening we visited another local church and briefly presented the ministry. The Wednesday after Labor Day we attended City Baptist Church of Albuquerque, and the following Wednesday we attended Bella Vista again. We stayed with family while in Albuquerque.'}},
 {id:'polarsteps-2025-carlsbad',targetId:'6vof0rrf5hb7j80qkjpvlcdko6',date:'2025-09-12',contactId:'mfst-clay-carlson-carlsbad',title:'Faith Baptist Church | Carlsbad, NM',fields:{preached:'yes',sermons:['The Reason They Stood','Activating the Trinity'],handout:'yes',outreach:'Weekend ministry and Bible handout',salvations:7,journal:'We spent the weekend with Faith Baptist Church in Carlsbad and Pastor Clay Carlson’s family. We arrived Friday and shared dinner and fellowship. Saturday morning’s Bible handout distributed more than 25 Bibles and six people were led to the Lord. A visitor named Zach, whom we met at the handout, attended Sunday morning, and one additional person was saved. I preached “The Reason They Stood” Sunday morning and “Activating the Trinity” Sunday evening. The church gave a generous love offering equivalent to ten months of support.'}},
 {id:'polarsteps-2025-old-paths',targetId:'8theie95n87bks94b5pfjlq55g',date:'2025-09-21',contactId:'mfst-phil-cavanaugh',title:'Old Paths Conference | Northwest Bible Baptist Church',fields:{preached:'no',outreach:'Taught a session on growing the Bible handout ministry',journal:'We attended the Old Paths Conference at Northwest Bible Baptist Church in Elgin. I did not preach in the main sessions, but every message was encouraging. Someone was baptized during Wednesday’s service. It was a special time reconnecting with friends and fellow alumni from the church where I graduated. I led a session on growing the Bible handout ministry, which went very well and helped equip pastors. This was the first event our whole family attended together since Haddon had been sick most of the year.'}},
 {id:'polarsteps-2025-campbell',date:'2025-09-26',end:'2025-09-28',contactId:'mfst-josh-lovens',title:'Calvary Baptist Church | Campbell, MO',fields:{preached:'yes',sermons:['Activating the Trinity','The Proven Pattern'],handout:'yes',outreach:'Bible handout, gospel presentations, and practical Bible-handout training',salvations:4,biblesPassed:54,lodging:'yes',journal:'We arrived Friday at the church parsonage and had dinner with Pastor and Mrs. Lovens, who had just moved into their new home. We were impressed by their spirit, attitude, and children. Saturday morning we attended the church sewing meeting and shared practical ideas about the Bible handout ministry. The handout stayed busy from beginning to end: 54 Bibles were distributed, more than 15 gospel presentations were given, and four people were saved. Andrew shared the gospel with a young lady and Abby prayed with her as she accepted Christ. That evening we enjoyed dinner, fellowship, and football with the Lovens family. I preached “Activating the Trinity” Sunday morning and the revival-focused message “The Proven Pattern” Sunday evening.'}},
 {id:'polarsteps-2025-fond-du-lac',targetId:'3322dqoqramn5pm7rjceoge0fk',date:'2025-10-01',contactId:'mfst-jack-barber',title:'Lighthouse Bible Baptist Church Revival | Fond du Lac, WI',fields:{preached:'yes',sermons:['The Proven Pattern',"Reciprocating God’s Faithfulness (Catching Paul’s Confidence)",'The Reason They Stood','The Battle for Dependence','Activating the Trinity','Faith Is the Victory'],handout:'yes',outreach:'Revival, Bible handout, and door-knocking',salvations:4,biblesPassed:40,journal:'Revival services ran Wednesday through Sunday with Pastor Jack Barber and his wife Taylor, who were wonderful hosts. Attendance was strong each night, with both familiar and new faces during our second consecutive year there. Saturday’s outreach distributed 40 Bibles. Three people were saved during the handout and one while door-knocking with Pastor Barber. A newer man in the church led his first soul to Christ. A couple who first visited during last year’s revival had since joined the church and were growing steadily; although sick during the week, they made a special effort to attend Sunday and fellowship with us.'}},
 {id:'polarsteps-2025-robins',targetId:'_clj62p1kc5gjeo9m61gj8phj6tgjcoj46di66ohh70q34e9p6oqg',date:'2025-10-08',contactId:'mfst-ken-koske',title:'Hope Baptist Church | Robins, IA',fields:{preached:'yes',sermons:['One Having Authority'],journal:'This was a Wednesday evening deputation visit. We showed the ministry video, presented the work, and I preached “One Having Authority.” The message seemed to encourage the church and resulted in a strong altar call. We reconnected with college friends Riley Robinson, Gabe Robinson, Cole Rowetter, and their wives. Afterward, Pastor Koske, Brother Gabe, and I shared a meal and fellowship at Chili’s. Pastor Koske expressed interest in hosting a Bible handout next year.'}},
 {id:'polarsteps-2025-oswego-handout',targetId:'b6qv0l10pse7frqegeilefkae8',date:'2025-10-11',contactId:'mfst-david-hemphill',title:'Bible Handout | Oswego, IL',fields:{handout:'yes',outreach:'Bible handout with Pastor David Hemphill',salvations:19,biblesPassed:50,journal:'We had a wonderful Bible handout with Pastor David Hemphill. More than 50 Bibles were passed out and 19 people were saved.'}},
 {id:'polarsteps-2025-rantoul',targetId:'64rg2gghfd2616b2v8mfto80q2',date:'2025-10-12',contactId:'mfst-mark-wilkerson',title:'Maranatha Baptist Church | Rantoul, IL',fields:{preached:'yes',handout:'yes',outreach:'Bible handout',salvations:10,biblesPassed:45,journal:'We held a Bible handout, distributing more than 45 Bibles and seeing more than ten people saved. I preached Sunday morning and Sunday evening.'}},
 {id:'polarsteps-2025-petoskey',targetId:'2adf4td05a73qf184vj3ekr77d',date:'2025-10-17',contactId:'mfst-ryan-rauhaus',title:'Landmark Baptist Church | Petoskey, MI',fields:{preached:'yes',handout:'no',outreach:'Soulwinning training after the Bible handout was canceled by rain',journal:'The planned Bible handout was canceled because of rain, so I conducted soulwinning training instead. I preached Sunday morning and Sunday evening.'}},
 {id:'polarsteps-2025-flora',targetId:'_clgm6phhclimcopk6hij8c9g70s68c1k75ij8chp70pjed9k74qg',date:'2025-10-22',contactId:'mfst-jesse-mccammon',title:'Calvary Baptist Church | Flora, IL',fields:{preached:'yes',journal:'I presented the ministry and preached.'}},
 {id:'polarsteps-2025-bourbonnais',targetId:'9tbhq6ovqkjvlf7t616gdu3big',date:'2025-10-26',contactId:'mfst-terry-anglea',title:'Homecoming Missions Conference | Faith Baptist Church',fields:{journal:'This missions conference gathered all missionaries sent out of Faith Baptist Church. Seven missionaries were able to attend with their families.'}},
 {id:'polarsteps-2025-moncofsky',targetId:'tfuc5vfmph0mvb91g1meadg7rs',date:'2025-11-01',contactId:'mfst-jason-moncofsky',title:'Grace Baptist Church | Missions Day',fields:{preached:'no',journal:'I did not preach during this visit.'}},
 {id:'polarsteps-2025-lebanon',targetId:'14hk5263q0hal1cl8af1jc5hum',date:'2025-11-05',contactId:'mfst-don-ball',title:'Tabernacle Baptist Church | Lebanon, MO',fields:{preached:'yes',journal:'I preached during this visit.'}},
 {id:'polarsteps-2025-mountain-grove',targetId:'7kfonht2mm25rs8koqdiun5d7e',date:'2025-11-07',contactId:'mfst-jerry-sousley',title:'Whetstone Baptist Church | Mountain Grove, MO',fields:{handout:'yes',outreach:'Bible handout',salvations:3,journal:'Three people were saved during the Bible handout.'}},
 {id:'polarsteps-2025-center-chapel',targetId:'bfrb0m4sesnbbiivhou3ac48t4',date:'2025-11-19',contactId:'mfst-danny-dodson',title:'School Chapel | Central Baptist Church, Center, TX',fields:{preached:'yes',sermons:['When You Meet God'],journal:'I preached “When You Meet God” in chapel.'}},
 {id:'polarsteps-2025-oswego-support',targetId:'iqqkh3tsopp4hfdnorpi0afp78',date:'2025-12-03',contactId:'mfst-david-hemphill',title:'Valley Baptist Church | Oswego, IL',fields:{preached:'yes',support:'yes',journal:'I preached, and the church took us on for support.'}},
 {id:'polarsteps-2025-tempe',targetId:'47t3bhj6nqfki5n2u7edvrc61c',date:'2025-12-12',contactId:'mfst-justin-leasure',title:'East Valley Baptist Church | Tempe, AZ',fields:{preached:'no',handout:'yes',outreach:'Six-hour Bible handout',salvations:2,biblesPassed:60,journal:'I did not preach. We conducted a six-hour Bible handout, distributed 60 Bibles, and saw two people saved.'}},
 {id:'polarsteps-2025-abq-christmas',targetId:'qbnnsebvc7t33j80q1u4no1dp0',date:'2025-12-20',contactId:'mfst-matt-hudson',title:'Bella Vista Baptist Church | Albuquerque, NM',fields:{preached:'yes',sermons:['Delivering the Greatest Gift'],journal:'I preached “Delivering the Greatest Gift.”'}},
 {id:'polarsteps-2025-las-cruces',targetId:'0p74s3944gli3v6fo689n7lmsa',date:'2025-12-28',contactId:'mfst-doug-cowen',title:'Cornerstone Baptist Church | Las Cruces, NM',fields:{preached:'yes',sermons:["I Just Can’t Help It"],journal:'I preached “I Just Can’t Help It.”'}},
 {id:'polarsteps-2025-new-heights',targetId:'iqcmppv5sep77u5s4fs2rpbgrc',date:'2025-12-28',contactId:'mfst-dave-reyes',title:'New Heights Baptist Church',fields:{preached:'yes',sermons:['Delivering the Greatest Gift'],journal:'I preached “Delivering the Greatest Gift.”'}}
];

const meaningful=v=>v!==undefined&&v!==null&&v!==''&&v!=='unknown';
function applyEntries(state,entries){
 if(!Array.isArray(state.calendarMeetings))state.calendarMeetings=[];
 for(const entry of entries){
  let meeting=entry.targetId?state.calendarMeetings.find(m=>m.id===entry.targetId):state.calendarMeetings.find(m=>m.contactId===entry.contactId&&m.date===entry.date);
  if(!meeting){meeting={id:entry.id,title:entry.title,date:entry.date,end:entry.end||entry.date,contactId:entry.contactId,kind:'meeting',source:'Polarsteps journal'};state.calendarMeetings.push(meeting);}
  if(!meeting.contactId&&entry.contactId)meeting.contactId=entry.contactId;
  const current=meeting.debrief||{},fields=entry.fields,journal=current.journal&&current.journal.includes(fields.journal)?current.journal:[current.journal,fields.journal].filter(Boolean).join('\n\n');
  meeting.debrief={...current,status:current.status||'completed',preached:meaningful(current.preached)?current.preached:(fields.preached||'unknown'),sermons:[...new Set([...(current.sermons||[]),...(fields.sermons||[])])],handout:meaningful(current.handout)?current.handout:(fields.handout||'unknown'),outreach:current.outreach||fields.outreach||'',salvations:current.salvations??fields.salvations??null,biblesPassed:current.biblesPassed??fields.biblesPassed??null,visitors:meaningful(current.visitors)?current.visitors:'unknown',lodging:meaningful(current.lodging)?current.lodging:(fields.lodging||'unknown'),support:meaningful(current.support)?current.support:(fields.support||'unknown'),journal,photo:current.photo||'',polarstepsUpdated:true,completedAt:current.completedAt||'2026-09-26T00:00:00.000Z',snoozedUntil:'',polarstepsImport:true};
 }
 return state;
}
export function applyPolarstepsHistory2024(state){
 applyEntries(state,HISTORY_2024);
 state.polarstepsHistory2024Applied=true;
 return state;
}
export function applyPolarstepsHistory2025(state){
 applyEntries(state,HISTORY_2025);
 state.polarstepsHistory2025Applied=true;
 return state;
}
